# Generated by Django 5.0.6 on 2024-10-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatrequest',
            unique_together=set(),
        ),
    ]
