# Generated by Django 5.0.6 on 2024-08-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_friends_user_sent_requests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
