# Generated by Django 5.0.6 on 2024-10-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chatrequest_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatrequest',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='price_not_equal_discount_price'),
        ),
    ]
