# Generated by Django 5.0.6 on 2024-10-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatrequest_price_not_equal_discount_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatrequest',
            name='price_not_equal_discount_price',
        ),
        migrations.AddConstraint(
            model_name='chatrequest',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='sender_not_equal_receiver'),
        ),
    ]
